### ISSUE TITLE
Parsing "null" or error gamepk

### ISSUE THREAD

**Issue by tonci-j** [tnestico/mlb_scraper#1]
In minor league levels from some older years there are gamepk (ex from 2018 and sport_id=[16]: https://statsapi.mlb.com/api/v1.1/game/550991/feed/live) that when opened have the following within:

{"messageNumber":13,"message":"Operation taking longer than expected - please try again","timestamp":"2024-12-06T18:59:04.411048647Z","traceId":null}

When one of these gamepk is processed through game_data = scraper.get_data(game_list_input=[550991]) and then attempted to convert to Dataframe (data_df = scraper.get_data_df(data_list=game_data)) the following happens:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python312\Lib\site-packages\api_scraper_mod.py", line 268, in get_data_df
    for ab_id in range(len(data['liveData']['plays']['allPlays'])):
                           ~~~~^^^^^^^^^^^^
KeyError: 'liveData'

I've run into more examples of corrupt gamepk as I've moved further back in time and needing to manually review and remove them is very tedious. Can you update the code to ignore these gamepk somehow?

**Comment by tnestico** [comment]
I added in a try/except condition to bypass any NULL games
